# Generated by Django 5.1.4 on 2026-09-28 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCalendarSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Přátelský název (např. „Pracovní Google", „Rodinný Apple").', max_length=100)),
                ('ical_url', models.URLField(help_text='Public iCal URL. Google Calendar Settings → Secret address in iCal format. Outlook: Settings → Shared calendars → Publish.', max_length=1000)),
                ('enabled', models.BooleanField(default=True, help_text='Vypnuté zdroje se nefetchují ani nezobrazují na canvasu.')),
                ('color', models.CharField(default='#0284c7', help_text='Hex color pro rozlišení zdrojů na canvasu (per user).', max_length=7)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='', help_text="Chybová hláška z posledního fetch, '' = OK.")),
                ('busy_blocks', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'personal_calendar_source',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['user', 'enabled'], name='personal_ca_user_id_7ce3f0_idx')],
            },
        ),
    ]
