# Generated by Django 5.1.4 on 2026-05-20 07:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GearItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('weight_g', models.PositiveIntegerField(blank=True, help_text='Weight in grams. NULL = unspecified.', null=True)),
                ('url', models.URLField(blank=True, default='', help_text='Optional product link (e-shop, manufacturer).', max_length=600)),
                ('category', models.CharField(blank=True, default='', help_text='Free-text grouping label (sleep / cooking / clothing / ...).', max_length=60)),
                ('note', models.TextField(blank=True, default='', help_text='Optional comment — color, size, why I like it.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gear_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gear_item',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GearList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gear_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gear_list',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GearListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('gear_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='gear.gearlist')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_entries', to='gear.gearitem')),
            ],
            options={
                'db_table': 'gear_list_item',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='gearlist',
            name='items',
            field=models.ManyToManyField(related_name='lists', through='gear.GearListItem', to='gear.gearitem'),
        ),
        migrations.AddIndex(
            model_name='gearitem',
            index=models.Index(fields=['user', 'category'], name='gear_item_user_id_4307c2_idx'),
        ),
        migrations.AddConstraint(
            model_name='gearlistitem',
            constraint=models.UniqueConstraint(fields=('gear_list', 'item'), name='uniq_item_per_gear_list'),
        ),
        migrations.AddIndex(
            model_name='gearlist',
            index=models.Index(fields=['user', 'name'], name='gear_list_user_id_44d64c_idx'),
        ),
    ]
