# Generated by Django 5.1.4 on 2026-05-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearlist',
            name='slug',
            field=models.SlugField(blank=True, max_length=22, unique=True),
        ),
        migrations.AddField(
            model_name='gearlist',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private — only the owner can see it'), ('unlisted', 'Unlisted — anyone with the URL can see it'), ('public', 'Public — indexable + share-friendly')], default='private', max_length=20),
        ),
    ]
