# Generated by Django 5.1.4 on 2026-05-20 08:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0003_backfill_slugs'),
    ]

    operations = [
        migrations.CreateModel(
            name='GearLinkClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_hash', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('referer', models.URLField(blank=True, default='', max_length=600)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='gear.gearlistitem')),
            ],
            options={
                'db_table': 'gear_link_click',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entry', 'created_at'], name='gear_link_c_entry_i_1c01e7_idx')],
            },
        ),
    ]
