# Generated by Django 5.1.4 on 2026-05-20 12:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0004_gearlinkclick'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gearitem',
            name='category',
            field=models.CharField(blank=True, default='', help_text='Denormalised category name for legacy reads.', max_length=60),
        ),
        migrations.CreateModel(
            name='GearCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gear_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gear_category',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='gearitem',
            name='category_obj',
            field=models.ForeignKey(blank=True, help_text='Canonical category — kept in sync with the string below.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='gear.gearcategory'),
        ),
        migrations.AddConstraint(
            model_name='gearcategory',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='uniq_category_per_user'),
        ),
    ]
