# Generated by Django 5.1.4 on 2026-05-21 10:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, help_text='Discriminator — see KIND_* constants for known values.', max_length=40)),
                ('title', models.CharField(help_text='Short one-line summary shown in the bell dropdown. Pre-formatted by the backend (incl. actor name etc.).', max_length=200)),
                ('body', models.TextField(blank=True, default='', help_text='Optional longer text for the expanded view.')),
                ('link', models.CharField(blank=True, default='', help_text='Relative frontend URL to navigate to on click (e.g. /events/ws/event/?tab=nastenka#topic-42).', max_length=500)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Kind-specific structured data (topic_id, event_slug, ...).')),
                ('read_at', models.DateTimeField(blank=True, db_index=True, help_text='Null = unread.', null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read_at', '-created_at'], name='notificatio_recipie_ce9d56_idx')],
            },
        ),
    ]
