# Generated by Django 5.1.4 on 2026-05-19 12:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_type', models.CharField(choices=[('workspace', 'Workspace'), ('event', 'Event')], max_length=20)),
                ('parent_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('pinned', models.BooleanField(default=False, help_text='Pinned topics sort to the top of the feed.')),
                ('locked', models.BooleanField(default=False, help_text="Locked topics don't accept new comments.")),
                ('comment_count', models.PositiveIntegerField(default=0, help_text='Denormalised — kept in sync by Comment.save/delete.')),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'discussions_topic',
                'ordering': ['-pinned', '-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussion_comments', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='discussions.topic')),
            ],
            options={
                'db_table': 'discussions_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['parent_type', 'parent_id', '-last_activity_at'], name='discussions_parent__e830d3_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['topic', 'created_at'], name='discussions_topic_i_546058_idx'),
        ),
    ]
