# Generated by Django 5.1.4 on 2026-05-19 14:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='discussions.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'discussions_topic_like',
                'indexes': [models.Index(fields=['topic', 'created_at'], name='discussions_topic_i_934f1d_idx')],
                'constraints': [models.UniqueConstraint(fields=('topic', 'user'), name='uniq_topic_like_per_user')],
            },
        ),
    ]
