# Generated by Django 5.1.4 on 2026-05-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0004_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional photo attached to the comment.', null=True, upload_to='discussions/comments/'),
        ),
    ]
