# Generated by Django 5.1.4 on 2026-05-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0005_comment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.FileField(blank=True, help_text='Optional file attached to the comment (image or other).', null=True, upload_to='discussions/comments/'),
        ),
    ]
