# Generated by Django 5.1.4 on 2026-09-25 19:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0006_alter_comment_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-pinned', '-created_at']},
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['parent_type', 'parent_id', '-created_at'], name='discussions_parent__594f01_idx'),
        ),
    ]
