# Generated by Django 5.1.4 on 2026-05-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_active_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='diet',
            field=models.CharField(blank=True, choices=[('omnivore', 'Omnivore'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='diet_note',
            field=models.TextField(blank=True, help_text='Alergie, intolerance, …'),
        ),
        migrations.AddField(
            model_name='user',
            name='fitness_note',
            field=models.TextField(blank=True, help_text='Krátká poznámka — cíl na sezónu, oblíbený typ běhání, …'),
        ),
        migrations.AddField(
            model_name='user',
            name='longest_run',
            field=models.CharField(blank=True, help_text='Nejdelší souvislý běh, např. "21 km", "půlmaraton".', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='pace_10k',
            field=models.CharField(blank=True, help_text='Čas na 10 km na rovince, např. "55:00".', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='tshirt_size',
            field=models.CharField(blank=True, help_text='XS / S / M / L / XL / XXL', max_length=8),
        ),
        migrations.AddField(
            model_name='user',
            name='weekly_km',
            field=models.PositiveIntegerField(blank=True, help_text='Průměrný týdenní objem v km.', null=True),
        ),
    ]
