# Generated by Django 5.1.4 on 2026-05-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_diet_user_diet_note_user_fitness_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='address_country',
            field=models.CharField(blank=True, default='CZ', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='address_street',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='address_zip',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='billing_city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='billing_country',
            field=models.CharField(blank=True, default='CZ', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='billing_dic',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='billing_ico',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='billing_name',
            field=models.CharField(blank=True, help_text='Company / person to bill (e.g. employer for B2B).', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='billing_street',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='billing_zip',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='has_billing_address',
            field=models.BooleanField(default=False),
        ),
    ]
