# Generated by Django 5.1.4 on 2026-05-19 09:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_address_city_user_address_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Krátký popisek — např. "Osobně" / "Olaf Adventures s.r.o.".', max_length=80)),
                ('legal_name', models.CharField(help_text='Jméno / název firmy, jak má být na faktuře.', max_length=200)),
                ('ico', models.CharField(blank=True, default='', max_length=15)),
                ('dic', models.CharField(blank=True, default='', max_length=15)),
                ('address_street', models.CharField(blank=True, default='', max_length=200)),
                ('address_city', models.CharField(blank=True, default='', max_length=120)),
                ('address_zip', models.CharField(blank=True, default='', max_length=20)),
                ('address_country', models.CharField(blank=True, default='CZ', max_length=2)),
                ('iban', models.CharField(blank=True, default='', max_length=34)),
                ('bank_name', models.CharField(blank=True, default='', max_length=80)),
                ('is_default', models.BooleanField(default=False, help_text='Default profile pre-selected when the user creates a new paid event. Only one default per user.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_billingprofile',
                'ordering': ['-is_default', 'label'],
                'indexes': [models.Index(fields=['user', 'is_default'], name='accounts_bi_user_id_eb3da9_idx')],
            },
        ),
    ]
