# Generated by Django 5.1.4 on 2026-05-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_billingprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_on_discussion_announce',
            field=models.BooleanField(default=True, help_text="Email me when a new topic appears in a komunita I'm a member of, or on an event I'm RSVP'd to."),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_on_discussion_reply',
            field=models.BooleanField(default=True, help_text='Email me when someone replies on a topic I started.'),
        ),
    ]
