# Generated by Django 5.1.4 on 2026-05-19 19:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_notify_on_discussion_announce_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=600, unique=True)),
                ('p256dh', models.CharField(help_text='ECDH P-256 public key, base64-url encoded.', max_length=200)),
                ('auth', models.CharField(help_text='Auth secret, base64-url encoded.', max_length=80)),
                ('user_agent', models.CharField(blank=True, default='', help_text='Captured at subscription time for the user-facing list.', max_length=300)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_used_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_push_subscription',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_pu_user_id_865d0e_idx')],
            },
        ),
    ]
