# Generated by Django 5.1.4 on 2026-05-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='affiliate_partners',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
