# Generated by Django 5.1.4 on 2026-05-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_affiliate_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notion_integration_token_encrypted',
            field=models.TextField(blank=True, default='', help_text='Fernet-encrypted Notion internal integration token. Used to fetch Notion pages when ingesting an event from a URL. User generates the token at notion.so/profile/integrations and pastes it into settings → integrace.'),
        ),
    ]
