# Generated by Django 5.1.4 on 2026-05-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_notion_integration_token_encrypted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='anthropic_api_key_encrypted',
            field=models.TextField(blank=True, default='', help_text="Fernet-encrypted Anthropic API key. Per-user so each creator's LLM calls go on their own bill — no shared platform key, no admin gating. User generates the key at console.anthropic.com and pastes into settings → integrace."),
        ),
    ]
