# Generated by Django 5.1.4 on 2026-05-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_anthropic_api_key_encrypted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_on_discussion_mention',
            field=models.BooleanField(default=True, help_text='Bell + e-mail when someone @-mentions me in a comment. Independent of the reply opt-out — mentions are louder.'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_on_event_update',
            field=models.BooleanField(default=True, help_text="Bell + e-mail when the organiser of an event I've RSVPed to changes a participant-visible field (date, location, price, etc.)."),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_on_rsvp_status',
            field=models.BooleanField(default=True, help_text='Bell when the owner approves or rejects my pending registration.'),
        ),
    ]
