# Generated by Django 5.1.4 on 2026-06-23 06:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_apitoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerHiddenPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'accounts_owner_hidden_person',
                'ordering': ['-hidden_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='apitoken',
            new_name='accounts_ap_user_id_f995a6_idx',
            old_name='accounts_ap_user_id_revoked_idx',
        ),
        migrations.AddField(
            model_name='ownerhiddenperson',
            name='owner',
            field=models.ForeignKey(help_text="The creator who clicked 'Skrýt z přehledu'.", on_delete=django.db.models.deletion.CASCADE, related_name='lide_hidden_people', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ownerhiddenperson',
            name='target',
            field=models.ForeignKey(help_text="The user being hidden from the owner's Lidé view.", on_delete=django.db.models.deletion.CASCADE, related_name='hidden_by_owners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ownerhiddenperson',
            index=models.Index(fields=['owner', '-hidden_at'], name='accounts_ow_owner_i_723140_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ownerhiddenperson',
            unique_together={('owner', 'target')},
        ),
    ]
