# Generated by Django 5.1.4 on 2026-06-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_ownerhiddenperson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profilová fotka — zobrazí se na landing page eventu, pokud je user vybraný jako organizátor.', null=True, upload_to='avatars/'),
        ),
    ]
