# Generated by Django 5.1.4 on 2026-05-21 13:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0007_workspace_public_invite_token_workspaceinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, help_text='Dotted action code, e.g. `event.soft_delete`.', max_length=80)),
                ('target_type', models.CharField(blank=True, default='', help_text='`event`, `rsvp`, `workspace_member`, …', max_length=40)),
                ('target_id', models.CharField(blank=True, default='', help_text='PK of the target row, stored as a string so we can hold ints, uuids, or composite keys without schema gymnastics.', max_length=80)),
                ('summary', models.CharField(help_text='Czech one-liner for the audit feed. Format: actor-less verb-first sentence, e.g. „Smazal akci Spring Camp".', max_length=300)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Structured context — e.g. for `event.update`, the list of changed fields and their before/after values.')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, help_text='Who performed the action. NULL when the action was a system/cron event (e.g., scheduled hard-purge) or when the user has since been deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, help_text='Tenant scope. NULL only for cross-tenant or platform-wide actions (none today). Used as the filter axis for the /admin/audit viewer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workspaces.workspace')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['workspace', '-created_at'], name='audit_ws_created_idx'), models.Index(fields=['target_type', 'target_id'], name='audit_target_idx')],
            },
        ),
    ]
