# Generated by Django 5.1.4 on 2026-05-13 11:40

import django.db.models.deletion
import django.utils.timezone
import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Lowercase, hyphenated. Unique within the workspace.', validators=[events.models.validate_event_slug])),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Plain text for now; rich-text/markdown editor lands later.')),
                ('cover', models.ImageField(blank=True, upload_to='events/covers/')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('tz', models.CharField(default='UTC', help_text='IANA timezone, e.g. Europe/Prague. Defaults to workspace tz.', max_length=50)),
                ('location_text', models.CharField(blank=True, max_length=300)),
                ('meeting_point_text', models.CharField(blank=True, max_length=300)),
                ('location_url', models.URLField(blank=True, help_text='Optional map link (Google Maps, Mapy.cz, etc.).', max_length=500)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Maximum confirmed RSVPs. Empty = unlimited.', null=True)),
                ('waitlist_enabled', models.BooleanField(default=True, help_text='When capacity is reached, additional RSVPs join a waitlist.')),
                ('visibility', models.CharField(choices=[('public', 'Public — anyone with the link can RSVP'), ('invite_only', 'Invite-only — emailed tokens only')], default='public', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft — visible only to the creator'), ('published', 'Published — RSVPs open'), ('closed', 'Closed — RSVPs no longer accepted'), ('cancelled', 'Cancelled'), ('completed', 'Completed (auto-transition after end)')], default='draft', max_length=20)),
                ('requires_approval', models.BooleanField(default=False, help_text='If true, RSVPs land in pending_approval until the Creator confirms.')),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'events_event',
                'ordering': ['-starts_at'],
                'indexes': [models.Index(fields=['workspace', 'status', 'starts_at'], name='events_even_workspa_ea0807_idx')],
                'unique_together': {('workspace', 'slug')},
            },
        ),
    ]
