# Generated by Django 5.1.4 on 2026-05-14 04:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='highlights',
            field=models.JSONField(blank=True, default=list, help_text='Bullet list of "what we\'ll focus on" (e.g. ["technika běhu", "regenerace", "výživa", "výbava"]).'),
        ),
        migrations.AddField(
            model_name='event',
            name='included',
            field=models.JSONField(blank=True, default=list, help_text='Bullet list of what\'s included in the price (["3 noci ubytování", "tréninky", "fotky", "snídaně + večeře"]).'),
        ),
        migrations.AddField(
            model_name='event',
            name='price_text',
            field=models.CharField(blank=True, help_text='Free-form price string for the landing page, e.g. "2 450 Kč".', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='program',
            field=models.JSONField(blank=True, default=list, help_text='Day-by-day program for the public landing page. Each entry is {"day": "Čtvrtek", "title": "Příjezd", "body": "Přijeď..."}.'),
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('yes', 'Confirmed'), ('maybe', 'Maybe'), ('no', 'Declined'), ('waitlist', 'On waitlist'), ('pending_approval', 'Pending creator approval'), ('cancelled', 'Cancelled')], default='yes', max_length=20)),
                ('questionnaire_answers', models.JSONField(blank=True, default=dict)),
                ('waitlist_position', models.PositiveIntegerField(blank=True, null=True)),
                ('attended', models.BooleanField(blank=True, help_text='Set by the Creator after the event.', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'events_rsvp',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['event', 'status'], name='events_rsvp_event_i_6bb8a2_idx'), models.Index(fields=['event', 'status', 'waitlist_position'], name='events_rsvp_event_i_d806cf_idx')],
                'unique_together': {('event', 'user')},
            },
        ),
    ]
