# Generated by Django 5.1.4 on 2026-05-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_highlights_event_included_event_price_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='enabled_questionnaire_sections',
            field=models.JSONField(blank=True, default=list, help_text="Which questionnaire sections appear on this event's RSVP form. Empty list = all sections enabled (backwards compat)."),
        ),
    ]
