# Generated by Django 5.1.4 on 2026-05-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_enabled_questionnaire_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='accommodation_info',
            field=models.TextField(blank=True, help_text='Kde se spí, typ ubytování, polopenze/snídaně, co je v ceně.'),
        ),
        migrations.AddField(
            model_name='event',
            name='additional_cost_note',
            field=models.CharField(blank=True, help_text='Rough estimate of extra costs, e.g. "~12 500 Kč/osoba navíc na ubytování a permity".', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='difficulty_level',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 = nezadáno, 1-5 = lehké → velmi náročné.'),
        ),
        migrations.AddField(
            model_name='event',
            name='difficulty_note',
            field=models.TextField(blank=True, help_text='Co konkrétně náročnost na této akci znamená — počet km/den, hodin chůze, převýšení, požadovaná kondice.'),
        ),
        migrations.AddField(
            model_name='event',
            name='faq',
            field=models.JSONField(blank=True, default=list, help_text='List of {"question": str, "answer": str} items.'),
        ),
        migrations.AddField(
            model_name='event',
            name='gear_info',
            field=models.TextField(blank=True, help_text='Co si vzít, co půjčíme/poskytneme, povinná × doporučená výbava.'),
        ),
        migrations.AddField(
            model_name='event',
            name='not_included',
            field=models.JSONField(blank=True, default=list, help_text='List of bullet items NOT covered by the price.'),
        ),
        migrations.AddField(
            model_name='event',
            name='transport_info',
            field=models.TextField(blank=True, help_text='Jak se na akci dostat, sraz, co se používá za dopravu během akce.'),
        ),
    ]
