# Generated by Django 5.1.4 on 2026-05-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_accommodation_info_event_additional_cost_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='blocks',
            field=models.JSONField(blank=True, default=list, help_text='List of {id, type, payload} content blocks. See events/blocks.py.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='gear_info',
            field=models.TextField(blank=True, help_text='Co si vzít, co půjčíme/poskytneme, povinná vs. doporučená výbava.'),
        ),
    ]
