# Generated by Django 5.1.4 on 2026-05-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
        ('events', '0006_eventimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='communities',
            field=models.ManyToManyField(blank=True, help_text='Communities under the workspace where this event is listed.', related_name='events', to='communities.community'),
        ),
    ]
