# Generated by Django 5.1.4 on 2026-05-18 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_data_migrate_legacy_to_blocks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='accommodation_info',
        ),
        migrations.RemoveField(
            model_name='event',
            name='additional_cost_note',
        ),
        migrations.RemoveField(
            model_name='event',
            name='difficulty_level',
        ),
        migrations.RemoveField(
            model_name='event',
            name='difficulty_note',
        ),
        migrations.RemoveField(
            model_name='event',
            name='faq',
        ),
        migrations.RemoveField(
            model_name='event',
            name='gear_info',
        ),
        migrations.RemoveField(
            model_name='event',
            name='highlights',
        ),
        migrations.RemoveField(
            model_name='event',
            name='included',
        ),
        migrations.RemoveField(
            model_name='event',
            name='not_included',
        ),
        migrations.RemoveField(
            model_name='event',
            name='price_text',
        ),
        migrations.RemoveField(
            model_name='event',
            name='program',
        ),
        migrations.RemoveField(
            model_name='event',
            name='transport_info',
        ),
    ]
