# Generated by Django 5.1.4 on 2026-05-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_event_accommodation_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Set price → event is paid. Null → event is free.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='price_currency',
            field=models.CharField(default='CZK', max_length=3),
        ),
        migrations.AddField(
            model_name='event',
            name='price_note',
            field=models.CharField(blank=True, default='', help_text='Short qualifier shown next to the price (e.g. "vč. DPH", "záloha 1 000 Kč").', max_length=120),
        ),
    ]
