# Generated by Django 5.1.4 on 2026-05-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_price_amount_event_price_currency_and_more'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='shared_workspaces',
            field=models.ManyToManyField(blank=True, help_text='Additional workspaces (komunity) where this event appears. Only workspaces the creator also owns may be added.', related_name='shared_events', to='workspaces.workspace'),
        ),
    ]
