# Generated by Django 5.1.4 on 2026-05-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_shared_workspaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='payment_currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='payment_due_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('waived', 'Waived')], default='waived', max_length=20),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='variable_symbol',
            field=models.CharField(blank=True, default='', help_text="Czech 'variabilní symbol' (max 10 digits) for QR Platba.", max_length=10),
        ),
    ]
