# Generated by Django 5.1.4 on 2026-05-19 07:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_rsvp_payment_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='required_documents',
            field=models.JSONField(blank=True, default=list, help_text='Documents required from participants: [{"key": "waiver", "label": "Souhlas s riziky", "required": true}, ...].'),
        ),
        migrations.CreateModel(
            name='RSVPDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Matches a key inside event.required_documents.', max_length=60)),
                ('file', models.FileField(upload_to='events/rsvp-docs/')),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rsvp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='events.rsvp')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_rsvp_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'events_rsvpdocument',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['rsvp', 'key'], name='events_rsvp_rsvp_id_8f26b7_idx')],
            },
        ),
    ]
