# Generated by Django 5.1.4 on 2026-05-19 07:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_event_required_documents_rsvpdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text="Public invoice number (e.g. 'OLAF-2026-0001').", max_length=40, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('void', 'Void')], default='issued', max_length=10)),
                ('supplier_name', models.CharField(max_length=200)),
                ('supplier_address', models.TextField(blank=True, default='')),
                ('supplier_ico', models.CharField(blank=True, default='', max_length=20)),
                ('supplier_dic', models.CharField(blank=True, default='', max_length=20)),
                ('supplier_iban', models.CharField(blank=True, default='', max_length=34)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_address', models.TextField(blank=True, default='')),
                ('customer_ico', models.CharField(blank=True, default='', max_length=20)),
                ('customer_dic', models.CharField(blank=True, default='', max_length=20)),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('items', models.JSONField(blank=True, default=list)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='CZK', max_length=3)),
                ('variable_symbol', models.CharField(blank=True, default='', max_length=10)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rsvp', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='events.rsvp')),
            ],
            options={
                'db_table': 'events_invoice',
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['rsvp'], name='events_invo_rsvp_id_eb58fb_idx')],
            },
        ),
    ]
