# Generated by Django 5.1.4 on 2026-05-19 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_billingprofile'),
        ('events', '0014_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='billing_profile',
            field=models.ForeignKey(blank=True, help_text='Owner picks which of their billing profiles to invoice from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='accounts.billingprofile'),
        ),
        migrations.AddField(
            model_name='event',
            name='payment_in_cash',
            field=models.BooleanField(default=False, help_text='Owner takes payment in cash on the day. Skips QR + invoice generation; payment status stays informational.'),
        ),
    ]
