# Generated by Django 5.1.4 on 2026-05-19 12:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_event_billing_profile_event_payment_in_cash'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, default='', help_text='Free-text grouping label (risk / gear / comms / ...).', max_length=40)),
                ('done', models.BooleanField(default=False)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='events.event')),
            ],
            options={
                'db_table': 'events_checklist_item',
                'ordering': ['done', 'sort_order', 'created_at'],
                'indexes': [models.Index(fields=['event', 'done'], name='events_chec_event_i_3a7f8e_idx')],
            },
        ),
    ]
