# Generated by Django 5.1.4 on 2026-05-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_eventchecklistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventchecklistitem',
            name='remind_at',
            field=models.DateTimeField(blank=True, help_text='When to dispatch the reminder e-mail. Null = no reminder.', null=True),
        ),
        migrations.AddField(
            model_name='eventchecklistitem',
            name='remind_audience',
            field=models.CharField(choices=[('creator', 'Creator (owner-only e-mail)'), ('participants', "Participants (RSVP'd users + owner)")], default='creator', max_length=20),
        ),
        migrations.AddField(
            model_name='eventchecklistitem',
            name='remind_sent_at',
            field=models.DateTimeField(blank=True, help_text='Stamped after dispatch_due_reminders sends the mail.', null=True),
        ),
        migrations.AddIndex(
            model_name='eventchecklistitem',
            index=models.Index(fields=['remind_at', 'remind_sent_at'], name='checklist_due_idx'),
        ),
    ]
