# Generated by Django 5.1.4 on 2026-05-20 07:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_fix_questionnaire_section_keys'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='enabled_questionnaire_sections',
            field=models.JSONField(blank=True, default=list, help_text="Which questionnaire sections appear on this event's RSVP form. Empty list = no questionnaire (form collects only user profile)."),
        ),
        migrations.CreateModel(
            name='EventCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_event_collaborators', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_collaborations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'events_event_collaborator',
                'ordering': ['created_at'],
                'unique_together': {('event', 'user')},
            },
        ),
    ]
