# Generated by Django 5.1.4 on 2026-05-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_alter_event_enabled_questionnaire_sections_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='is_organizer',
            field=models.BooleanField(db_index=True, default=False, help_text="Doesn't count toward capacity, exempt from payment + docs."),
        ),
    ]
