# Generated by Django 5.1.4 on 2026-05-20 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_rsvp_is_organizer'),
        ('gear', '0006_backfill_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recommended_gear_list',
            field=models.ForeignKey(blank=True, help_text='Optional GearList shown to participants as a packing checklist.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_for_events', to='gear.gearlist'),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='gear_checklist',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
