# Generated by Django 5.1.4 on 2026-05-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_event_recommended_gear_list_rsvp_gear_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='risk_checklist',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
