# Generated by Django 5.1.4 on 2026-05-21 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_periodic_complete_finished_events'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Set when the owner soft-deletes the event. NULL = alive. Rows with deleted_at older than 30 days are hard-purged by the `events.purge_old_soft_deletes` Celery task.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='Audit pointer — who soft-deleted this event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
