# Generated by Django 5.1.4 on 2026-06-11 10:37
import uuid

from django.db import migrations, models


def backfill_tokens(apps, schema_editor):
    """Existing RSVPs nemají token → vygenerujeme jim unikátní UUID.
    Bez tohohle by `unique=True` constraint po `AlterField` selhal,
    protože všechny rows by měly stejnou default-uuid hodnotu (Django
    při AddField volá default jednou pro celý ALTER, ne per row)."""
    RSVP = apps.get_model("events", "RSVP")
    for rsvp in RSVP.objects.all().only("pk"):
        rsvp.cancel_token = uuid.uuid4()
        rsvp.save(update_fields=["cancel_token"])


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_periodic_purge_old_soft_deletes'),
    ]

    operations = [
        # 1) Přidáme pole bez `unique` constraintu — všechny rows tím
        #    dostanou stejnou default hodnotu.
        migrations.AddField(
            model_name="rsvp",
            name="cancel_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        # 2) RunPython přepíše každou row na unikátní UUID.
        migrations.RunPython(backfill_tokens, reverse_code=migrations.RunPython.noop),
        # 3) Teprve teď zapneme `unique=True` + db index.
        migrations.AlterField(
            model_name="rsvp",
            name="cancel_token",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                db_index=True,
            ),
        ),
    ]
