# Generated by Django 5.1.4 on 2026-06-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_rsvp_cancel_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('self', 'Self'), ('by_token', 'Via magic-link'), ('owner', 'Owner')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
