# Generated by Django 5.1.4 on 2026-06-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_rsvp_cancellation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='duplicate_dismissed',
            field=models.BooleanField(default=False),
        ),
    ]
