# Generated by Django 5.1.4 on 2026-06-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_rsvp_duplicate_dismissed'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='require_phone_on_rsvp',
            field=models.BooleanField(default=True, help_text='Vyžadovat telefon při registraci. Default True kvůli emergencies (pořadatel potřebuje sehnat účastníka v terénu). U casual akcí (opékání špekáčků, komunita) si owner odznačí.'),
        ),
    ]
