# Generated by Django 5.1.4 on 2026-08-18 07:28

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def backfill_feedback_tokens(apps, schema_editor):
    """Existing RSVPs nemají token → vygenerujeme jim unikátní UUID.
    Stejný pattern jako 0028_rsvp_cancel_token — bez toho by `unique=True`
    AlterField spadl (Django při AddField volá default jen jednou pro
    celou tabulku, ne per row)."""
    RSVP = apps.get_model("events", "RSVP")
    for rsvp in RSVP.objects.all().only("pk"):
        rsvp.feedback_token = uuid.uuid4()
        rsvp.save(update_fields=["feedback_token"])


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_rsvp_document_rejected_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name="rsvp",
            name="feedback_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(
            backfill_feedback_tokens,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="rsvp",
            name="feedback_token",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                db_index=True,
            ),
        ),
        migrations.CreateModel(
            name='EventFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('went_well', models.TextField(blank=True, default='')),
                ('could_improve', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='events.event')),
                ('rsvp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='events.rsvp')),
            ],
            options={
                'db_table': 'events_event_feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', '-created_at'], name='events_even_event_i_b66aa6_idx')],
            },
        ),
    ]
