# Generated by Django 5.1.4 on 2026-08-19 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0035_eventlink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventchecklistitem',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_checklist_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventchecklistitem',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventchecklistitem',
            name='remind_audience',
            field=models.CharField(choices=[('creator', 'Creator (owner-only e-mail)'), ('participants', "Participants (RSVP'd users + owner)"), ('assignee', 'Assignee (jen přiřazený uživatel)')], default='creator', max_length=20),
        ),
    ]
