# Generated by Django 5.1.4 on 2026-08-20 14:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0036_eventchecklistitem_assignee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('expected_paying_count', models.PositiveIntegerField(blank=True, null=True)),
                ('margin_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='costing', to='events.event')),
            ],
            options={
                'db_table': 'events_event_costing',
            },
        ),
        migrations.CreateModel(
            name='EventCostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('fixed', 'Fixní částka'), ('per_person', 'Na osobu')], default='fixed', max_length=20)),
                ('planned_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, default='', max_length=400)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('costing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='events.eventcosting')),
            ],
            options={
                'db_table': 'events_event_cost_item',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
