# Generated by Django 5.1.4 on 2026-05-18 06:42

import communities.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Lowercase, hyphenated. Unique within the workspace.', validators=[communities.models.validate_community_slug])),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cover', models.ImageField(blank=True, upload_to='communities/covers/')),
                ('visibility', models.CharField(choices=[('private', 'Private — invite-only, hidden'), ('unlisted', 'Unlisted — link-only, hidden from lists'), ('public', 'Public — visible, anyone can request to join')], default='private', max_length=20)),
                ('membership_policy', models.CharField(choices=[('approval', 'Approval-based — request → owner approves'), ('invite_only', 'Invite-only — emailed token to join')], default='approval', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'communities_community',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CommunityMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending — awaiting approval'), ('member', 'Member — accepted'), ('declined', 'Declined — user said no'), ('removed', 'Removed — owner removed them')], default='pending', max_length=20)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='communities.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'communities_communitymember',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['workspace', 'slug'], name='communities_workspa_f05569_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='community',
            unique_together={('workspace', 'slug')},
        ),
        migrations.AddIndex(
            model_name='communitymember',
            index=models.Index(fields=['community', 'status'], name='communities_communi_cbc300_idx'),
        ),
        migrations.AddIndex(
            model_name='communitymember',
            index=models.Index(fields=['user', 'status'], name='communities_user_id_dd6c21_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='communitymember',
            unique_together={('community', 'user')},
        ),
    ]
