# Generated by Django 5.1.4 on 2026-05-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymember',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin — community management'), ('member', 'Member — regular member')], default='member', help_text='Community-level role within an active membership. Backfill promotes the first member (chronologically) of each existing community to admin so V1 communities always have an explicit manager beyond the workspace owner.', max_length=20),
        ),
    ]
