from django.urls import path

from . import views

app_name = "events"

urlpatterns = [
    path("mine/", views.my_events, name="mine"),
    path("owner/", views.owner_events, name="owner"),
    path("trash/", views.deleted_events_list, name="trash"),
    # Magic-link RSVP cancel pro guest registranty. Musí být deklarovaný
    # PŘED `<slug:workspace_slug>/<slug:event_slug>/` workspace-scoped
    # patterny, jinak by `rsvp/cancel-by-token/` matchnul jako
    # `workspace_slug=rsvp, event_slug=cancel-by-token` → 405 z
    # public_event view-u.
    path(
        "rsvp/cancel-by-token/",
        views.cancel_rsvp_by_token,
        name="rsvp-cancel-by-token",
    ),
    path(
        "from-source/",
        views.ingest_event_from_source,
        name="from-source",
    ),
    path(
        "import-schema/",
        views.import_schema,
        name="import-schema",
    ),
    path(
        "<slug:workspace_slug>/create/",
        views.create_event,
        name="create",
    ),
    path(
        "<slug:workspace_slug>/import/",
        views.import_event,
        name="import",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/",
        views.public_event,
        name="public",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/update/",
        views.update_event,
        name="update",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/sync-from-source/",
        views.sync_event_from_source,
        name="sync-from-source",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/link-notion/",
        views.link_event_to_notion,
        name="link-notion",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/cover/",
        views.event_cover,
        name="cover",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/duplicate/",
        views.duplicate_event,
        name="duplicate",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/images/",
        views.event_images,
        name="images",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/images/reorder/",
        views.event_images_reorder,
        name="images-reorder",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/images/<int:image_id>/",
        views.event_image_detail,
        name="image-detail",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/block-images/",
        views.event_block_image_upload,
        name="block-image-upload",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/cancel/",
        views.cancel_event,
        name="cancel",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/delete/",
        views.soft_delete_event,
        name="soft-delete",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/restore/",
        views.restore_event,
        name="restore",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/purge/",
        views.purge_event,
        name="purge",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/rsvp/",
        views.rsvp_event,
        name="rsvp",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/rsvp/cancel/",
        views.cancel_my_rsvp,
        name="rsvp-cancel",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/rsvps/",
        views.event_rsvps,
        name="rsvps",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/rsvps/<int:rsvp_id>/profile/",
        views.participant_profile,
        name="rsvp-profile",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/collaborators/",
        views.event_collaborators,
        name="collaborators",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/collaborators/<int:user_id>/",
        views.event_collaborator_detail,
        name="collaborator-detail",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/organizer-pool/",
        views.event_organizer_pool,
        name="organizer-pool",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/rsvps/<int:rsvp_id>/approve/",
        views.approve_rsvp,
        name="rsvp-approve",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/rsvps/<int:rsvp_id>/reject/",
        views.reject_rsvp,
        name="rsvp-reject",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/rsvps/<int:rsvp_id>/remove/",
        views.remove_rsvp,
        name="rsvp-remove",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/rsvps/<int:rsvp_id>/duplicate-dismiss/",
        views.dismiss_duplicate_hint,
        name="rsvp-duplicate-dismiss",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/rsvp/payment/",
        views.my_rsvp_payment,
        name="rsvp-payment",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/rsvp/payment/qr.png",
        views.my_rsvp_payment_qr,
        name="rsvp-payment-qr",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/rsvps/<int:rsvp_id>/mark-paid/",
        views.mark_rsvp_paid,
        name="rsvp-mark-paid",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/rsvps/<int:rsvp_id>/organizer/",
        views.toggle_rsvp_organizer,
        name="rsvp-toggle-organizer",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/rsvp/gear-checklist/",
        views.rsvp_gear_checklist,
        name="rsvp-gear-checklist",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/rsvp/documents/",
        views.my_rsvp_documents,
        name="rsvp-documents",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/rsvp/documents/<int:document_id>/",
        views.my_rsvp_document_detail,
        name="rsvp-document-detail",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/invoices/",
        views.event_invoices,
        name="invoices",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/invoices/<int:invoice_id>/",
        views.invoice_detail,
        name="invoice-detail",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/invoices/<int:invoice_id>/pdf/",
        views.invoice_pdf,
        name="invoice-pdf",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/invoices/<int:invoice_id>/qr.png",
        views.invoice_qr,
        name="invoice-qr",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/rsvp/invoice/",
        views.my_invoice,
        name="my-invoice",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/checklist/",
        views.event_checklist,
        name="checklist",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/checklist/items/",
        views.checklist_items,
        name="checklist-items",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/checklist/items/<int:item_id>/",
        views.checklist_item_detail,
        name="checklist-item-detail",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/checklist/items/<int:item_id>/send-now/",
        views.checklist_item_send_now,
        name="checklist-item-send-now",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/checklist/from-preset/",
        views.checklist_from_preset,
        name="checklist-from-preset",
    ),
    path(
        "<slug:workspace_slug>/payments/bulk-match/",
        views.bulk_match_payments,
        name="payments-bulk-match",
    ),
]
