from django.urls import path

from . import views

app_name = "events"

urlpatterns = [
    path("mine/", views.my_events, name="mine"),
    path("owner/", views.owner_events, name="owner"),
    path(
        "<slug:workspace_slug>/create/",
        views.create_event,
        name="create",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/",
        views.public_event,
        name="public",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/update/",
        views.update_event,
        name="update",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/cover/",
        views.event_cover,
        name="cover",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/duplicate/",
        views.duplicate_event,
        name="duplicate",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/images/",
        views.event_images,
        name="images",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/images/reorder/",
        views.event_images_reorder,
        name="images-reorder",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/images/<int:image_id>/",
        views.event_image_detail,
        name="image-detail",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/block-images/",
        views.event_block_image_upload,
        name="block-image-upload",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/cancel/",
        views.cancel_event,
        name="cancel",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/rsvp/",
        views.rsvp_event,
        name="rsvp",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/rsvp/cancel/",
        views.cancel_my_rsvp,
        name="rsvp-cancel",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/rsvps/",
        views.event_rsvps,
        name="rsvps",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/rsvps/<int:rsvp_id>/approve/",
        views.approve_rsvp,
        name="rsvp-approve",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/rsvps/<int:rsvp_id>/reject/",
        views.reject_rsvp,
        name="rsvp-reject",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/rsvp/payment/",
        views.my_rsvp_payment,
        name="rsvp-payment",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/rsvp/payment/qr.png",
        views.my_rsvp_payment_qr,
        name="rsvp-payment-qr",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/rsvps/<int:rsvp_id>/mark-paid/",
        views.mark_rsvp_paid,
        name="rsvp-mark-paid",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/rsvp/documents/",
        views.my_rsvp_documents,
        name="rsvp-documents",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/rsvp/documents/<int:document_id>/",
        views.my_rsvp_document_detail,
        name="rsvp-document-detail",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/invoices/",
        views.event_invoices,
        name="invoices",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/invoices/<int:invoice_id>/",
        views.invoice_detail,
        name="invoice-detail",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/invoices/<int:invoice_id>/pdf/",
        views.invoice_pdf,
        name="invoice-pdf",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/invoices/<int:invoice_id>/qr.png",
        views.invoice_qr,
        name="invoice-qr",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/rsvp/invoice/",
        views.my_invoice,
        name="my-invoice",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/checklist/",
        views.event_checklist,
        name="checklist",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/checklist/items/",
        views.checklist_items,
        name="checklist-items",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/checklist/items/<int:item_id>/",
        views.checklist_item_detail,
        name="checklist-item-detail",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/checklist/items/<int:item_id>/send-now/",
        views.checklist_item_send_now,
        name="checklist-item-send-now",
    ),
    path(
        "<slug:workspace_slug>/<slug:event_slug>/checklist/from-preset/",
        views.checklist_from_preset,
        name="checklist-from-preset",
    ),
]
