# Generated by Django 5.1.4 on 2026-05-13 04:55

import django.db.models.deletion
import django.utils.timezone
import workspaces.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Lowercase, hyphenated. Used in URLs.', unique=True, validators=[workspaces.validators.validate_workspace_slug])),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('accent_color', models.CharField(blank=True, help_text='Hex like #RRGGBB.', max_length=7)),
                ('logo', models.ImageField(blank=True, upload_to='workspaces/logos/')),
                ('cover', models.ImageField(blank=True, upload_to='workspaces/covers/')),
                ('visibility', models.CharField(choices=[('public', 'Public — indexable, listed on the platform'), ('unlisted', 'Unlisted — accessible only with a direct link'), ('private', 'Private — 404 to non-members')], default='public', max_length=10)),
                ('default_tz', models.CharField(default='UTC', help_text='IANA timezone, e.g. Europe/Prague.', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workspaces_workspace',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner')], default='owner', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'workspaces_workspace_member',
                'ordering': ['workspace', 'user_id'],
                'unique_together': {('workspace', 'user')},
            },
        ),
    ]
