# Generated by Django 5.1.4 on 2026-05-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='payment_bank_name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='workspace',
            name='payment_due_days',
            field=models.PositiveIntegerField(default=14, help_text='Days from registration the participant has to pay.'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='payment_iban',
            field=models.CharField(blank=True, default='', help_text='IBAN where participants send event payments (CZ format supported).', max_length=34),
        ),
    ]
