# Generated by Django 5.1.4 on 2026-05-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_seed_olaf_adventures'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='is_personal',
            field=models.BooleanField(db_index=True, default=False, help_text='Lazy-created on first event when the user has no community.'),
        ),
    ]
