# Generated by Django 5.1.4 on 2026-05-20 10:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_alter_workspacemember_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('color', models.CharField(blank=True, default='', help_text='Optional color token or hex; UI falls back to brand if blank.', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_tags', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'workspaces_person_tag',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PersonProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_profiles', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_profiles', to='workspaces.workspace')),
                ('tags', models.ManyToManyField(blank=True, related_name='profiles', to='workspaces.persontag')),
            ],
            options={
                'db_table': 'workspaces_person_profile',
            },
        ),
        migrations.AddConstraint(
            model_name='persontag',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='uniq_tag_name_per_workspace'),
        ),
        migrations.AlterUniqueTogether(
            name='personprofile',
            unique_together={('workspace', 'user')},
        ),
    ]
