# Generated by Django 5.1.4 on 2026-06-22 18:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0007_workspace_public_invite_token_workspaceinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemember',
            name='joined_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('removed', 'Removed')], default='active', max_length=20),
        ),
    ]
