# Generated by Django 5.1.4 on 2026-06-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0009_backfill_explicit_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='event_sharing_policy',
            field=models.CharField(choices=[('admin_only', 'Pouze admini komunity'), ('members', 'Všichni členové komunity')], default='admin_only', help_text='Kdo smí do téhle komunity sdílet události.', max_length=20),
        ),
    ]
