# Generated by Django 5.1.4 on 2026-09-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0014_workspace_cover_focal'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='workspaceslugalias',
            new_name='workspaces__old_slu_a04833_idx',
            old_name='workspaces__old_slu_idx',
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workspacemember',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('removed', 'Removed'), ('pending', 'Pending — awaiting approval')], default='active', max_length=20),
        ),
    ]
