# Generated by Django 5.1.4 on 2026-09-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0015_workspacemember_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='logo_transparent',
            field=models.BooleanField(default=False),
        ),
    ]
