# Generated by Django 5.1.4 on 2026-09-26 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0016_workspace_logo_transparent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='parent_community',
            field=models.ForeignKey(blank=True, help_text="Parent komunita v hierarchii. Když parent_link_status='active', členové této komunity jsou effective members parent komunity.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_communities', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='parent_link_status',
            field=models.CharField(blank=True, choices=[('', 'Bez parenta'), ('pending', 'Pending — čeká na schválení parent adminem'), ('active', 'Active — link platný')], db_index=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='workspace',
            name='parent_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='parent_requested_by',
            field=models.ForeignKey(blank=True, help_text='User (child admin), kdo iniciovali request na parent.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
