# Generated by Django 5.1.4 on 2026-09-26 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Oficiální jméno závodu (např. „UTMB", „Beskydská 7").', max_length=200)),
                ('slug', models.SlugField(help_text='URL slug — auto-generováno z jména, může se přepsat.', max_length=250, unique=True)),
                ('date_start', models.DateField(db_index=True, help_text='První den závodu / start.')),
                ('date_end', models.DateField(blank=True, help_text='Poslední den (u vícedenních). Prázdné = jednodenní.', null=True)),
                ('distance_km', models.PositiveIntegerField(help_text='Délka trati v km (integer, zaokrouhli nahoru).')),
                ('elevation_m', models.PositiveIntegerField(blank=True, help_text='Celkové převýšení v metrech (D+). Prázdné = neuvedeno.', null=True)),
                ('terrain', models.CharField(blank=True, default='', help_text='Terén — trail / mountain / road / skyrace / desert. Volné pole pro flexibilitu, filtruje se full-text.', max_length=60)),
                ('location', models.CharField(blank=True, default='', help_text='Místo (např. „Beskydy, Frenštát p. Radhoštěm").', max_length=200)),
                ('country', models.CharField(blank=True, db_index=True, default='', help_text='Země (Česko, Slovensko, Francie…). Filtrujeme podle toho.', max_length=100)),
                ('url', models.URLField(blank=True, default='', help_text='Oficiální stránka závodu (registrace, program).')),
                ('series', models.CharField(choices=[('indep', 'Nezávislý'), ('utmb', 'UTMB World Series'), ('wtm', 'World Trail Majors'), ('sky', 'Skyrunner Series'), ('major', 'Major (bez série)')], db_index=True, default='indep', max_length=20)),
                ('registration_status', models.CharField(choices=[('open', 'Přihlášky otevřeny'), ('lottery', 'Losování'), ('sold_out', 'Vyprodáno'), ('qualifier', 'Nutná kvalifikace'), ('closed', 'Přihlášky uzavřeny')], default='open', max_length=20)),
                ('highlight', models.CharField(blank=True, default='', help_text='1-2 věty co je zajímavé (např. „Klasika v Beskydech, přesně 100 km, 5 000 D+"). Zobrazuje se v listě pod jménem.', max_length=280)),
                ('is_visible', models.BooleanField(db_index=True, default=True, help_text='Soft-hide bez smazání (např. při chybném importu).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Závod',
                'verbose_name_plural': 'Závody',
                'db_table': 'races_race',
                'ordering': ['date_start', 'name'],
                'indexes': [models.Index(fields=['is_visible', 'date_start'], name='races_race_is_visi_7c5c91_idx'), models.Index(fields=['country', 'date_start'], name='races_race_country_47f137_idx'), models.Index(fields=['series'], name='races_race_series_de15c7_idx')],
            },
        ),
        migrations.CreateModel(
            name='RaceFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='races.race')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oblíbený závod',
                'verbose_name_plural': 'Oblíbené závody',
                'db_table': 'races_favorite',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'race')},
            },
        ),
    ]
