# Generated by Django 5.1.4 on 2026-09-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0003_import_ultra_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='has_warning',
            field=models.BooleanField(default=False, help_text='Data mají neurčitost (zrušeno/nejisté/pauza).'),
        ),
        migrations.AddField(
            model_name='race',
            name='is_top',
            field=models.BooleanField(db_index=True, default=False, help_text='Flagship race — vlajkový závod pro Top výběr.'),
        ),
        migrations.AddField(
            model_name='race',
            name='next_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='race',
            name='next_year',
            field=models.PositiveIntegerField(db_index=True, default=2027),
        ),
        migrations.AddField(
            model_name='race',
            name='registration_detail',
            field=models.TextField(blank=True, default='', help_text='Full description of how registration works.'),
        ),
        migrations.AlterField(
            model_name='race',
            name='registration_status',
            field=models.CharField(choices=[('open', 'Přihlášky otevřeny'), ('lottery', 'Losování'), ('sold_out', 'Vyprodáno'), ('qualifier', 'Nutná kvalifikace'), ('closed', 'Přihlášky uzavřeny'), ('unknown', 'Nejasné / TBA')], default='open', max_length=20),
        ),
    ]
