# Generated by Django 5.1.4 on 2026-09-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0006_split_skpl_to_sk_pl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='racefavorite',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Race plán', 'verbose_name_plural': 'Race plány'},
        ),
        migrations.AddField(
            model_name='racefavorite',
            name='note',
            field=models.CharField(blank=True, default='', help_text='Osobní poznámka (např. „jedu s Martou, letenka koupená").', max_length=280),
        ),
        migrations.AddField(
            model_name='racefavorite',
            name='status',
            field=models.CharField(choices=[('interested', 'Zajímá mě'), ('waiting_registration', 'Čekám na registraci'), ('registered', 'Registrován'), ('waitlist', 'Na waitlistu'), ('completed', 'Absolvoval')], db_index=True, default='interested', help_text='Vztah uživatele k závodu (interested → completed).', max_length=30),
        ),
        migrations.AddField(
            model_name='racefavorite',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='region',
            field=models.CharField(blank=True, choices=[('CZ', 'Česko'), ('SK', 'Slovensko'), ('PL', 'Polsko'), ('ALP', 'Alpy'), ('SEV', 'Skandinávie / sever'), ('IBE', 'Ibérie'), ('BAL', 'Balkán / Řecko'), ('OST', 'Ostrovy'), ('SVET', 'Svět')], db_index=True, default='', max_length=10),
        ),
    ]
