# Generated by Django 5.1.4 on 2026-09-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0007_racefavorite_status_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('local', 'Local seed_data.json'), ('remote', 'Remote GitHub raw')], default='local', max_length=20)),
                ('source_url', models.URLField(blank=True, default='', help_text='Přesná URL, ze které se fetchovalo (remote případy).')),
                ('status', models.CharField(choices=[('ok', 'OK'), ('error', 'Chyba'), ('partial', 'Částečný úspěch')], default='ok', max_length=20)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('flagged_count', models.PositiveIntegerField(default=0, help_text='Počet races které dostaly has_warning=True kvůli contradiction detection.')),
                ('error_message', models.TextField(blank=True, default='')),
                ('changes', models.JSONField(blank=True, default=list, help_text='List of {slug, field, old, new} objects — konkrétní změny detected. Zobrazí se v admin diff view.')),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('triggered_by', models.CharField(default='beat', help_text='`beat` (periodic task) / `manual` / `signal` (deploy hook).', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Sync běh',
                'verbose_name_plural': 'Sync běhy',
                'db_table': 'races_sync_run',
                'ordering': ['-created_at'],
            },
        ),
    ]
