# Generated by Django 5.1.4 on 2026-09-29 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0008_syncrun'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=1000)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('ai_response_raw', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending — čeká na admin review'), ('approved', 'Approved — Race vytvořen'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, default='', help_text='Admin poznámka při approve/reject.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_race', models.ForeignKey(blank=True, help_text='Race vytvořený po approve (aby šlo dohledat submission).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='races.race')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Race submission',
                'verbose_name_plural': 'Race submissions',
                'db_table': 'races_submission',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='races_submi_status_2bc9e7_idx'), models.Index(fields=['user', 'created_at'], name='races_submi_user_id_bf8c1f_idx')],
            },
        ),
    ]
