# Generated by Django 5.1.4 on 2026-06-25 07:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0033_rsvp_document_rejected_fields'),
        ('workspaces', '0009_backfill_explicit_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Lidové jméno šablony — „Smlouva o účasti", "Souhlas s riziky", …', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Interní poznámka pro tvůrce — kdy tuhle šablonu použít.')),
                ('body_html', models.TextField(blank=True, help_text='HTML šablony s placeholdery {{ucastnik_jmeno}} apod. Render přes Django Template engine.')),
                ('notion_url', models.URLField(blank=True, help_text='Volitelně — Notion stránka co drží zdroj. „Sync z Notion" ji znovu načte přes Claude a přepíše body_html.')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_templates_created', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_templates', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'contracts_template',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EventContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_send_after_rsvp', models.BooleanField(default=False, help_text='True = po každém novém RSVP backend vygeneruje smlouvu a pošle účastníkovi podpisový link. False = owner pošle ručně z rosteru.')),
                ('require_before_payment', models.BooleanField(default=False, help_text='True = účastník nemůže označit platbu dokud nepodepíše (V1.5 — zatím jen flag, vynucení později).')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='events.event')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_contracts', to='contracts.contracttemplate')),
            ],
            options={
                'db_table': 'contracts_event',
            },
        ),
        migrations.CreateModel(
            name='RSVPContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Posláno k podpisu'), ('signed', 'Podepsáno'), ('rejected', 'Odmítnuto účastníkem'), ('expired', 'Vypršelo')], db_index=True, default='pending', max_length=20)),
                ('generated_pdf', models.FileField(blank=True, null=True, upload_to='contracts/generated/')),
                ('signy_document_id', models.CharField(blank=True, default='', max_length=120)),
                ('signing_url', models.URLField(blank=True, default='')),
                ('signed_pdf', models.FileField(blank=True, null=True, upload_to='contracts/signed/')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvp_contracts', to='contracts.eventcontract')),
                ('rsvp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='events.rsvp')),
            ],
            options={
                'db_table': 'contracts_rsvp',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contracttemplate',
            index=models.Index(fields=['workspace', 'name'], name='contracts_t_workspa_fd1b97_idx'),
        ),
        migrations.AddIndex(
            model_name='rsvpcontract',
            index=models.Index(fields=['rsvp'], name='contracts_r_rsvp_id_d41ed3_idx'),
        ),
        migrations.AddIndex(
            model_name='rsvpcontract',
            index=models.Index(fields=['signy_document_id'], name='contracts_r_signy_d_15a993_idx'),
        ),
    ]
